services:
  - type: web
    name: beatfund
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: APP_ENV
        value: prod
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: beatfund-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /

databases:
  - name: beatfund-db
    databaseName: beatfund
    user: beatfund
    plan: free

